
package exception.runtime.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnexpectedErrorService", targetNamespace = "http://runtime.exception/", wsdlLocation = "http://127.0.0.1:2222/unexpectedError?wsdl")
public class UnexpectedErrorService
    extends Service
{

    private final static URL UNEXPECTEDERRORSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNEXPECTEDERRORSERVICE_EXCEPTION;
    private final static QName UNEXPECTEDERRORSERVICE_QNAME = new QName("http://runtime.exception/", "UnexpectedErrorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:2222/unexpectedError?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNEXPECTEDERRORSERVICE_WSDL_LOCATION = url;
        UNEXPECTEDERRORSERVICE_EXCEPTION = e;
    }

    public UnexpectedErrorService() {
        super(__getWsdlLocation(), UNEXPECTEDERRORSERVICE_QNAME);
    }

    public UnexpectedErrorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNEXPECTEDERRORSERVICE_QNAME, features);
    }

    public UnexpectedErrorService(URL wsdlLocation) {
        super(wsdlLocation, UNEXPECTEDERRORSERVICE_QNAME);
    }

    public UnexpectedErrorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNEXPECTEDERRORSERVICE_QNAME, features);
    }

    public UnexpectedErrorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnexpectedErrorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnexpectedError
     */
    @WebEndpoint(name = "UnexpectedErrorPort")
    public UnexpectedError getUnexpectedErrorPort() {
        return super.getPort(new QName("http://runtime.exception/", "UnexpectedErrorPort"), UnexpectedError.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnexpectedError
     */
    @WebEndpoint(name = "UnexpectedErrorPort")
    public UnexpectedError getUnexpectedErrorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://runtime.exception/", "UnexpectedErrorPort"), UnexpectedError.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNEXPECTEDERRORSERVICE_EXCEPTION!= null) {
            throw UNEXPECTEDERRORSERVICE_EXCEPTION;
        }
        return UNEXPECTEDERRORSERVICE_WSDL_LOCATION;
    }

}
