
package exception.checked.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExpectedError", targetNamespace = "http://checked.exception/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExpectedError {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     * @throws ZeroParameterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://checked.exception/", className = "exception.checked.client.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://checked.exception/", className = "exception.checked.client.DivisionResponse")
    @Action(input = "http://checked.exception/ExpectedError/divisionRequest", output = "http://checked.exception/ExpectedError/divisionResponse", fault = {
        @FaultAction(className = ZeroParameterException_Exception.class, value = "http://checked.exception/ExpectedError/division/Fault/ZeroParameterException")
    })
    public double division(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws ZeroParameterException_Exception
    ;

}
