
package exception.runtime.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UnexpectedError", targetNamespace = "http://runtime.exception/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnexpectedError {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operation", targetNamespace = "http://runtime.exception/", className = "exception.runtime.client.Operation")
    @ResponseWrapper(localName = "operationResponse", targetNamespace = "http://runtime.exception/", className = "exception.runtime.client.OperationResponse")
    @Action(input = "http://runtime.exception/UnexpectedError/operationRequest", output = "http://runtime.exception/UnexpectedError/operationResponse")
    public String operation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
