
package async.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AwesomeServiceWrappedDocumentService", targetNamespace = "http://service.wrapped.document.style/", wsdlLocation = "http://127.0.0.1:7890/wrapped?wsdl")
public class AwesomeServiceWrappedDocumentService
    extends Service
{

    private final static URL AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_EXCEPTION;
    private final static QName AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_QNAME = new QName("http://service.wrapped.document.style/", "AwesomeServiceWrappedDocumentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7890/wrapped?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_WSDL_LOCATION = url;
        AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_EXCEPTION = e;
    }

    public AwesomeServiceWrappedDocumentService() {
        super(__getWsdlLocation(), AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_QNAME);
    }

    public AwesomeServiceWrappedDocumentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_QNAME, features);
    }

    public AwesomeServiceWrappedDocumentService(URL wsdlLocation) {
        super(wsdlLocation, AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_QNAME);
    }

    public AwesomeServiceWrappedDocumentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_QNAME, features);
    }

    public AwesomeServiceWrappedDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AwesomeServiceWrappedDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AwesomeServiceWrappedDocument
     */
    @WebEndpoint(name = "AwesomeServiceWrappedDocumentPort")
    public AwesomeServiceWrappedDocument getAwesomeServiceWrappedDocumentPort() {
        return super.getPort(new QName("http://service.wrapped.document.style/", "AwesomeServiceWrappedDocumentPort"), AwesomeServiceWrappedDocument.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AwesomeServiceWrappedDocument
     */
    @WebEndpoint(name = "AwesomeServiceWrappedDocumentPort")
    public AwesomeServiceWrappedDocument getAwesomeServiceWrappedDocumentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wrapped.document.style/", "AwesomeServiceWrappedDocumentPort"), AwesomeServiceWrappedDocument.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_EXCEPTION!= null) {
            throw AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_EXCEPTION;
        }
        return AWESOMESERVICEWRAPPEDDOCUMENTSERVICE_WSDL_LOCATION;
    }

}
