
package async.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AwesomeServiceWrappedDocument", targetNamespace = "http://service.wrapped.document.style/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AwesomeServiceWrappedDocument {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<async.client.Operation1Response>
     */
    @WebMethod(operationName = "operation1")
    @RequestWrapper(localName = "operation1", targetNamespace = "http://service.wrapped.document.style/", className = "async.client.Operation1")
    @ResponseWrapper(localName = "operation1Response", targetNamespace = "http://service.wrapped.document.style/", className = "async.client.Operation1Response")
    public Response<Operation1Response> operation1Async(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "operation1")
    @RequestWrapper(localName = "operation1", targetNamespace = "http://service.wrapped.document.style/", className = "async.client.Operation1")
    @ResponseWrapper(localName = "operation1Response", targetNamespace = "http://service.wrapped.document.style/", className = "async.client.Operation1Response")
    public Future<?> operation1Async(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<Operation1Response> asyncHandler);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operation1", targetNamespace = "http://service.wrapped.document.style/", className = "async.client.Operation1")
    @ResponseWrapper(localName = "operation1Response", targetNamespace = "http://service.wrapped.document.style/", className = "async.client.Operation1Response")
    @Action(input = "http://service.wrapped.document.style/AwesomeServiceWrappedDocument/operation1Request", output = "http://service.wrapped.document.style/AwesomeServiceWrappedDocument/operation1Response")
    public int operation1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
