
package overloaded.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeManagement", targetNamespace = "http://service.overloaded/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManagement {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeEmployeeByName", targetNamespace = "http://service.overloaded/", className = "overloaded.client.RemoveEmployeeByName")
    @ResponseWrapper(localName = "removeEmployeeByNameResponse", targetNamespace = "http://service.overloaded/", className = "overloaded.client.RemoveEmployeeByNameResponse")
    @Action(input = "http://service.overloaded/EmployeeManagement/removeEmployeeByNameRequest", output = "http://service.overloaded/EmployeeManagement/removeEmployeeByNameResponse")
    public boolean removeEmployeeByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeEmployeeById", targetNamespace = "http://service.overloaded/", className = "overloaded.client.RemoveEmployeeById")
    @ResponseWrapper(localName = "removeEmployeeByIdResponse", targetNamespace = "http://service.overloaded/", className = "overloaded.client.RemoveEmployeeByIdResponse")
    @Action(input = "http://service.overloaded/EmployeeManagement/removeEmployeeByIdRequest", output = "http://service.overloaded/EmployeeManagement/removeEmployeeByIdResponse")
    public boolean removeEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
