
package overloaded.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeManagementService", targetNamespace = "http://service.overloaded/", wsdlLocation = "http://127.0.0.1:4567/EmployeeManagement?wsdl")
public class EmployeeManagementService
    extends Service
{

    private final static URL EMPLOYEEMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEMANAGEMENTSERVICE_EXCEPTION;
    private final static QName EMPLOYEEMANAGEMENTSERVICE_QNAME = new QName("http://service.overloaded/", "EmployeeManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:4567/EmployeeManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEMANAGEMENTSERVICE_WSDL_LOCATION = url;
        EMPLOYEEMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public EmployeeManagementService() {
        super(__getWsdlLocation(), EMPLOYEEMANAGEMENTSERVICE_QNAME);
    }

    public EmployeeManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEMANAGEMENTSERVICE_QNAME, features);
    }

    public EmployeeManagementService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEMANAGEMENTSERVICE_QNAME);
    }

    public EmployeeManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEMANAGEMENTSERVICE_QNAME, features);
    }

    public EmployeeManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeManagement
     */
    @WebEndpoint(name = "EmployeeManagementPort")
    public EmployeeManagement getEmployeeManagementPort() {
        return super.getPort(new QName("http://service.overloaded/", "EmployeeManagementPort"), EmployeeManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeManagement
     */
    @WebEndpoint(name = "EmployeeManagementPort")
    public EmployeeManagement getEmployeeManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.overloaded/", "EmployeeManagementPort"), EmployeeManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEMANAGEMENTSERVICE_EXCEPTION;
        }
        return EMPLOYEEMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
