
package style.rpc.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AwesomeServiceRPCService", targetNamespace = "http://service.rpc.style/", wsdlLocation = "http://127.0.0.1:9876/rpc?wsdl")
public class AwesomeServiceRPCService
    extends Service
{

    private final static URL AWESOMESERVICERPCSERVICE_WSDL_LOCATION;
    private final static WebServiceException AWESOMESERVICERPCSERVICE_EXCEPTION;
    private final static QName AWESOMESERVICERPCSERVICE_QNAME = new QName("http://service.rpc.style/", "AwesomeServiceRPCService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9876/rpc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AWESOMESERVICERPCSERVICE_WSDL_LOCATION = url;
        AWESOMESERVICERPCSERVICE_EXCEPTION = e;
    }

    public AwesomeServiceRPCService() {
        super(__getWsdlLocation(), AWESOMESERVICERPCSERVICE_QNAME);
    }

    public AwesomeServiceRPCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AWESOMESERVICERPCSERVICE_QNAME, features);
    }

    public AwesomeServiceRPCService(URL wsdlLocation) {
        super(wsdlLocation, AWESOMESERVICERPCSERVICE_QNAME);
    }

    public AwesomeServiceRPCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AWESOMESERVICERPCSERVICE_QNAME, features);
    }

    public AwesomeServiceRPCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AwesomeServiceRPCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AwesomeServiceRPC
     */
    @WebEndpoint(name = "AwesomeServiceRPCPort")
    public AwesomeServiceRPC getAwesomeServiceRPCPort() {
        return super.getPort(new QName("http://service.rpc.style/", "AwesomeServiceRPCPort"), AwesomeServiceRPC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AwesomeServiceRPC
     */
    @WebEndpoint(name = "AwesomeServiceRPCPort")
    public AwesomeServiceRPC getAwesomeServiceRPCPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.rpc.style/", "AwesomeServiceRPCPort"), AwesomeServiceRPC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AWESOMESERVICERPCSERVICE_EXCEPTION!= null) {
            throw AWESOMESERVICERPCSERVICE_EXCEPTION;
        }
        return AWESOMESERVICERPCSERVICE_WSDL_LOCATION;
    }

}
