
package style.document.bare.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AwesomeServiceBareDocumentService", targetNamespace = "http://service.bare.document.style/", wsdlLocation = "http://127.0.0.1:8765/bare?wsdl")
public class AwesomeServiceBareDocumentService
    extends Service
{

    private final static URL AWESOMESERVICEBAREDOCUMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException AWESOMESERVICEBAREDOCUMENTSERVICE_EXCEPTION;
    private final static QName AWESOMESERVICEBAREDOCUMENTSERVICE_QNAME = new QName("http://service.bare.document.style/", "AwesomeServiceBareDocumentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8765/bare?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AWESOMESERVICEBAREDOCUMENTSERVICE_WSDL_LOCATION = url;
        AWESOMESERVICEBAREDOCUMENTSERVICE_EXCEPTION = e;
    }

    public AwesomeServiceBareDocumentService() {
        super(__getWsdlLocation(), AWESOMESERVICEBAREDOCUMENTSERVICE_QNAME);
    }

    public AwesomeServiceBareDocumentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AWESOMESERVICEBAREDOCUMENTSERVICE_QNAME, features);
    }

    public AwesomeServiceBareDocumentService(URL wsdlLocation) {
        super(wsdlLocation, AWESOMESERVICEBAREDOCUMENTSERVICE_QNAME);
    }

    public AwesomeServiceBareDocumentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AWESOMESERVICEBAREDOCUMENTSERVICE_QNAME, features);
    }

    public AwesomeServiceBareDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AwesomeServiceBareDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AwesomeServiceBareDocument
     */
    @WebEndpoint(name = "AwesomeServiceBareDocumentPort")
    public AwesomeServiceBareDocument getAwesomeServiceBareDocumentPort() {
        return super.getPort(new QName("http://service.bare.document.style/", "AwesomeServiceBareDocumentPort"), AwesomeServiceBareDocument.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AwesomeServiceBareDocument
     */
    @WebEndpoint(name = "AwesomeServiceBareDocumentPort")
    public AwesomeServiceBareDocument getAwesomeServiceBareDocumentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bare.document.style/", "AwesomeServiceBareDocumentPort"), AwesomeServiceBareDocument.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AWESOMESERVICEBAREDOCUMENTSERVICE_EXCEPTION!= null) {
            throw AWESOMESERVICEBAREDOCUMENTSERVICE_EXCEPTION;
        }
        return AWESOMESERVICEBAREDOCUMENTSERVICE_WSDL_LOCATION;
    }

}
