
package customized.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Arithmetic", targetNamespace = "http://service.customized/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Arithmetic {


    /**
     * 
     * @param name
     * @param code
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "id", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.customized/", className = "customized.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.customized/", className = "customized.client.AddResponse")
    @Action(input = "http://service.customized/Arithmetic/addRequest", output = "http://service.customized/Arithmetic/addResponse")
    public long add(
        @WebParam(name = "code", targetNamespace = "")
        String code,
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
