
package style.rpc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AwesomeServiceRPC", targetNamespace = "http://service.rpc.style/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AwesomeServiceRPC {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.rpc.style/AwesomeServiceRPC/operation1Request", output = "http://service.rpc.style/AwesomeServiceRPC/operation1Response")
    public int operation1(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        long arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.rpc.style/AwesomeServiceRPC/operation2Request", output = "http://service.rpc.style/AwesomeServiceRPC/operation2Response")
    public int operation2(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
