
package oneway.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OneWayService", targetNamespace = "http://service.oneway/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OneWayService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "noReturnOperation", targetNamespace = "http://service.oneway/", className = "oneway.client.NoReturnOperation")
    @Action(input = "http://service.oneway/OneWayService/noReturnOperation")
    public void noReturnOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
