
package oneway.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OneWayServiceService", targetNamespace = "http://service.oneway/", wsdlLocation = "http://127.0.0.1:1234/oneway?wsdl")
public class OneWayServiceService
    extends Service
{

    private final static URL ONEWAYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ONEWAYSERVICESERVICE_EXCEPTION;
    private final static QName ONEWAYSERVICESERVICE_QNAME = new QName("http://service.oneway/", "OneWayServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1234/oneway?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ONEWAYSERVICESERVICE_WSDL_LOCATION = url;
        ONEWAYSERVICESERVICE_EXCEPTION = e;
    }

    public OneWayServiceService() {
        super(__getWsdlLocation(), ONEWAYSERVICESERVICE_QNAME);
    }

    public OneWayServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ONEWAYSERVICESERVICE_QNAME, features);
    }

    public OneWayServiceService(URL wsdlLocation) {
        super(wsdlLocation, ONEWAYSERVICESERVICE_QNAME);
    }

    public OneWayServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ONEWAYSERVICESERVICE_QNAME, features);
    }

    public OneWayServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OneWayServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OneWayService
     */
    @WebEndpoint(name = "OneWayServicePort")
    public OneWayService getOneWayServicePort() {
        return super.getPort(new QName("http://service.oneway/", "OneWayServicePort"), OneWayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OneWayService
     */
    @WebEndpoint(name = "OneWayServicePort")
    public OneWayService getOneWayServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.oneway/", "OneWayServicePort"), OneWayService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ONEWAYSERVICESERVICE_EXCEPTION!= null) {
            throw ONEWAYSERVICESERVICE_EXCEPTION;
        }
        return ONEWAYSERVICESERVICE_WSDL_LOCATION;
    }

}
