
package customized.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArithmeticService", targetNamespace = "http://service.customized/", wsdlLocation = "http://127.0.0.1:3456/customService?wsdl")
public class ArithmeticService
    extends Service
{

    private final static URL ARITHMETICSERVICE_WSDL_LOCATION;
    private final static WebServiceException ARITHMETICSERVICE_EXCEPTION;
    private final static QName ARITHMETICSERVICE_QNAME = new QName("http://service.customized/", "ArithmeticService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:3456/customService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARITHMETICSERVICE_WSDL_LOCATION = url;
        ARITHMETICSERVICE_EXCEPTION = e;
    }

    public ArithmeticService() {
        super(__getWsdlLocation(), ARITHMETICSERVICE_QNAME);
    }

    public ArithmeticService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARITHMETICSERVICE_QNAME, features);
    }

    public ArithmeticService(URL wsdlLocation) {
        super(wsdlLocation, ARITHMETICSERVICE_QNAME);
    }

    public ArithmeticService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARITHMETICSERVICE_QNAME, features);
    }

    public ArithmeticService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArithmeticService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Arithmetic
     */
    @WebEndpoint(name = "ArithmeticOperations")
    public Arithmetic getArithmeticOperations() {
        return super.getPort(new QName("http://service.customized/", "ArithmeticOperations"), Arithmetic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Arithmetic
     */
    @WebEndpoint(name = "ArithmeticOperations")
    public Arithmetic getArithmeticOperations(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.customized/", "ArithmeticOperations"), Arithmetic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARITHMETICSERVICE_EXCEPTION!= null) {
            throw ARITHMETICSERVICE_EXCEPTION;
        }
        return ARITHMETICSERVICE_WSDL_LOCATION;
    }

}
