
package secure.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Secure", targetNamespace = "http://service.secure/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Secure {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorldRestricted", targetNamespace = "http://service.secure/", className = "secure.client.HelloWorldRestricted")
    @ResponseWrapper(localName = "helloWorldRestrictedResponse", targetNamespace = "http://service.secure/", className = "secure.client.HelloWorldRestrictedResponse")
    @Action(input = "http://service.secure/Secure/helloWorldRestrictedRequest", output = "http://service.secure/Secure/helloWorldRestrictedResponse")
    public String helloWorldRestricted(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://service.secure/", className = "secure.client.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://service.secure/", className = "secure.client.HelloWorldResponse")
    @Action(input = "http://service.secure/Secure/helloWorldRequest", output = "http://service.secure/Secure/helloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
