
package exception.checked.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExpectedErrorService", targetNamespace = "http://checked.exception/", wsdlLocation = "http://127.0.0.1:3456/expectedError?wsdl")
public class ExpectedErrorService
    extends Service
{

    private final static URL EXPECTEDERRORSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXPECTEDERRORSERVICE_EXCEPTION;
    private final static QName EXPECTEDERRORSERVICE_QNAME = new QName("http://checked.exception/", "ExpectedErrorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:3456/expectedError?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPECTEDERRORSERVICE_WSDL_LOCATION = url;
        EXPECTEDERRORSERVICE_EXCEPTION = e;
    }

    public ExpectedErrorService() {
        super(__getWsdlLocation(), EXPECTEDERRORSERVICE_QNAME);
    }

    public ExpectedErrorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPECTEDERRORSERVICE_QNAME, features);
    }

    public ExpectedErrorService(URL wsdlLocation) {
        super(wsdlLocation, EXPECTEDERRORSERVICE_QNAME);
    }

    public ExpectedErrorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPECTEDERRORSERVICE_QNAME, features);
    }

    public ExpectedErrorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpectedErrorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExpectedError
     */
    @WebEndpoint(name = "ExpectedErrorPort")
    public ExpectedError getExpectedErrorPort() {
        return super.getPort(new QName("http://checked.exception/", "ExpectedErrorPort"), ExpectedError.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExpectedError
     */
    @WebEndpoint(name = "ExpectedErrorPort")
    public ExpectedError getExpectedErrorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://checked.exception/", "ExpectedErrorPort"), ExpectedError.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPECTEDERRORSERVICE_EXCEPTION!= null) {
            throw EXPECTEDERRORSERVICE_EXCEPTION;
        }
        return EXPECTEDERRORSERVICE_WSDL_LOCATION;
    }

}
