
package style.document.wrapped.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AwesomeServiceWrappedDocument", targetNamespace = "http://service.wrapped.document.style/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AwesomeServiceWrappedDocument {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operation1", targetNamespace = "http://service.wrapped.document.style/", className = "style.document.wrapped.client.Operation1")
    @ResponseWrapper(localName = "operation1Response", targetNamespace = "http://service.wrapped.document.style/", className = "style.document.wrapped.client.Operation1Response")
    @Action(input = "http://service.wrapped.document.style/AwesomeServiceWrappedDocument/operation1Request", output = "http://service.wrapped.document.style/AwesomeServiceWrappedDocument/operation1Response")
    public int operation1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
